/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiError {
    #[serde(rename = "is_fatal")]
    pub is_fatal: bool,
    #[serde(rename = "serial")]
    pub serial: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "error_code")]
    pub error_code: String,
    #[serde(rename = "error_msg")]
    pub error_msg: String,
}

impl ApiError {
    pub fn new(is_fatal: bool, serial: String, status: String, error_code: String, error_msg: String) -> ApiError {
        ApiError {
            is_fatal,
            serial,
            status,
            error_code,
            error_msg,
        }
    }
}


