/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CdromUpdateRequest {
    #[serde(rename = "CDROM")]
    pub CDROM: crate::models::CdromUpdateRequestBody,
}

impl CdromUpdateRequest {
    pub fn new(CDROM: crate::models::CdromUpdateRequestBody) -> CdromUpdateRequest {
        CdromUpdateRequest {
            CDROM,
        }
    }
}


