/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CdromWrapper {
    #[serde(rename = "CDROM")]
    pub CDROM: crate::models::Cdrom,
}

impl CdromWrapper {
    pub fn new(CDROM: crate::models::Cdrom) -> CdromWrapper {
        CdromWrapper {
            CDROM,
        }
    }
}


