/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CdromCreateResponse {
    #[serde(rename = "is_ok")]
    pub is_ok: bool,
    #[serde(rename = "CDROM")]
    pub CDROM: crate::models::Cdrom,
    #[serde(rename = "FTPServer")]
    pub ftp_server: crate::models::FtpServerDetailBody,
}

impl CdromCreateResponse {
    pub fn new(is_ok: bool, CDROM: crate::models::Cdrom, ftp_server: crate::models::FtpServerDetailBody) -> CdromCreateResponse {
        CdromCreateResponse {
            is_ok,
            CDROM,
            ftp_server,
        }
    }
}


