/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CdromsWrapper {
    #[serde(rename = "CDROMs")]
    pub cdroms: Vec<crate::models::Cdrom>,
}

impl CdromsWrapper {
    pub fn new(cdroms: Vec<crate::models::Cdrom>) -> CdromsWrapper {
        CdromsWrapper {
            cdroms,
        }
    }
}


