/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FtpServerDetailBody {
    #[serde(rename = "HostName")]
    pub host_name: String,
    #[serde(rename = "IPAddress")]
    pub ip_address: String,
    #[serde(rename = "User")]
    pub user: String,
    #[serde(rename = "Password")]
    pub password: String,
}

impl FtpServerDetailBody {
    pub fn new(host_name: String, ip_address: String, user: String, password: String) -> FtpServerDetailBody {
        FtpServerDetailBody {
            host_name,
            ip_address,
            user,
            password,
        }
    }
}


