/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FtpServer {
    #[serde(rename = "FTPServer")]
    pub ftp_server: crate::models::FtpServerBody,
}

impl FtpServer {
    pub fn new(ftp_server: crate::models::FtpServerBody) -> FtpServer {
        FtpServer {
            ftp_server,
        }
    }
}


