/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IconFindFilter {
    #[serde(rename = "Scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<crate::models::Scope>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "Tags.Name", skip_serializing_if = "Option::is_none")]
    pub tags_name: Option<Vec<String>>,
}

impl IconFindFilter {
    pub fn new() -> IconFindFilter {
        IconFindFilter {
            scope: None,
            name: None,
            tags_name: None,
        }
    }
}


