/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IconMultiResponse {
    #[serde(rename = "Count")]
    pub count: i32,
    #[serde(rename = "From")]
    pub from: i32,
    #[serde(rename = "Total")]
    pub total: i32,
    #[serde(rename = "is_ok")]
    pub is_ok: bool,
    #[serde(rename = "Icons")]
    pub icons: Vec<crate::models::Icon>,
}

impl IconMultiResponse {
    pub fn new(count: i32, from: i32, total: i32, is_ok: bool, icons: Vec<crate::models::Icon>) -> IconMultiResponse {
        IconMultiResponse {
            count,
            from,
            total,
            is_ok,
            icons,
        }
    }
}


