/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IconCreateRequestBody {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "Image")]
    pub image: String,
}

impl IconCreateRequestBody {
    pub fn new(name: String, image: String) -> IconCreateRequestBody {
        IconCreateRequestBody {
            name,
            tags: None,
            image,
        }
    }
}


