/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IconSingleResponse {
    #[serde(rename = "is_ok")]
    pub is_ok: bool,
    #[serde(rename = "Icon")]
    pub icon: crate::models::Icon,
}

impl IconSingleResponse {
    pub fn new(is_ok: bool, icon: crate::models::Icon) -> IconSingleResponse {
        IconSingleResponse {
            is_ok,
            icon,
        }
    }
}


