/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Icon {
    #[serde(rename = "Availability")]
    pub availability: String,
    #[serde(rename = "CreatedAt")]
    pub created_at: String,
    #[serde(rename = "ID")]
    pub ID: crate::models::Id,
    #[serde(rename = "ModifiedAt")]
    pub modified_at: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Scope")]
    pub scope: String,
    #[serde(rename = "Tags")]
    pub tags: Vec<String>,
    #[serde(rename = "URL")]
    pub URL: String,
}

impl Icon {
    pub fn new(availability: String, created_at: String, ID: crate::models::Id, modified_at: String, name: String, scope: String, tags: Vec<String>, URL: String) -> Icon {
        Icon {
            availability,
            created_at,
            ID,
            modified_at,
            name,
            scope,
            tags,
            URL,
        }
    }
}


