/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdEnvelope {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<crate::models::Id>,
}

impl IdEnvelope {
    pub fn new() -> IdEnvelope {
        IdEnvelope {
            ID: None,
        }
    }
}


