/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionWrapper {
    #[serde(rename = "Region")]
    pub region: crate::models::Region,
}

impl RegionWrapper {
    pub fn new(region: crate::models::Region) -> RegionWrapper {
        RegionWrapper {
            region,
        }
    }
}


