/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionsWrapper {
    #[serde(rename = "Regions")]
    pub regions: Vec<crate::models::Region>,
}

impl RegionsWrapper {
    pub fn new(regions: Vec<crate::models::Region>) -> RegionsWrapper {
        RegionsWrapper {
            regions,
        }
    }
}


