/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionSingleResponse {
    #[serde(rename = "is_ok")]
    pub is_ok: bool,
    #[serde(rename = "Region")]
    pub region: crate::models::Region,
}

impl RegionSingleResponse {
    pub fn new(is_ok: bool, region: crate::models::Region) -> RegionSingleResponse {
        RegionSingleResponse {
            is_ok,
            region,
        }
    }
}


