/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VncProxy {
    #[serde(rename = "HostName")]
    pub host_name: String,
    #[serde(rename = "IPAddress")]
    pub ip_address: String,
}

impl VncProxy {
    pub fn new(host_name: String, ip_address: String) -> VncProxy {
        VncProxy {
            host_name,
            ip_address,
        }
    }
}


