/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Zone {
    #[serde(rename = "CreatedAt")]
    pub created_at: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DisplayOrder")]
    pub display_order: i32,
    #[serde(rename = "FTPServer")]
    pub ftp_server: crate::models::FtpServerBody,
    #[serde(rename = "ID")]
    pub ID: crate::models::Id,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Region")]
    pub region: crate::models::Region,
    #[serde(rename = "VNCProxy")]
    pub vnc_proxy: crate::models::VncProxy,
    #[serde(rename = "IsDummy")]
    pub is_dummy: bool,
}

impl Zone {
    pub fn new(created_at: String, description: String, display_order: i32, ftp_server: crate::models::FtpServerBody, ID: crate::models::Id, name: String, region: crate::models::Region, vnc_proxy: crate::models::VncProxy, is_dummy: bool) -> Zone {
        Zone {
            created_at,
            description,
            display_order,
            ftp_server,
            ID,
            name,
            region,
            vnc_proxy,
            is_dummy,
        }
    }
}


