/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZoneWrapper {
    #[serde(rename = "Zone")]
    pub zone: crate::models::Zone,
}

impl ZoneWrapper {
    pub fn new(zone: crate::models::Zone) -> ZoneWrapper {
        ZoneWrapper {
            zone,
        }
    }
}


