/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZonesWrapper {
    #[serde(rename = "Zones")]
    pub zones: Vec<crate::models::Zone>,
}

impl ZonesWrapper {
    pub fn new(zones: Vec<crate::models::Zone>) -> ZonesWrapper {
        ZonesWrapper {
            zones,
        }
    }
}


