/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZoneFindFilter {
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<Vec<String>>,
    #[serde(rename = "Region.Name", skip_serializing_if = "Option::is_none")]
    pub region_name: Option<Vec<String>>,
    #[serde(rename = "Region.ID", skip_serializing_if = "Option::is_none")]
    pub region_id: Option<Vec<String>>,
}

impl ZoneFindFilter {
    pub fn new() -> ZoneFindFilter {
        ZoneFindFilter {
            name: None,
            ID: None,
            region_name: None,
            region_id: None,
        }
    }
}


