/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZoneFindRequestAllOf {
    #[serde(rename = "Filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<crate::models::ZoneFindFilter>,
}

impl ZoneFindRequestAllOf {
    pub fn new() -> ZoneFindRequestAllOf {
        ZoneFindRequestAllOf {
            filter: None,
        }
    }
}


