/*
 * SAKURA Cloud APIs
 *
 * This is a definitions for SAKURA Cloud APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sacloud.users@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZoneSingleResponse {
    #[serde(rename = "is_ok")]
    pub is_ok: bool,
    #[serde(rename = "Zone")]
    pub zone: crate::models::Zone,
}

impl ZoneSingleResponse {
    pub fn new(is_ok: bool, zone: crate::models::Zone) -> ZoneSingleResponse {
        ZoneSingleResponse {
            is_ok,
            zone,
        }
    }
}


