openapi: "3.0.3"
info:
  title: SAKURA Cloud APIs
  version: 0.0.1
  description: This is a definitions for SAKURA Cloud APIs.
  termsOfService: https://www.sakura.ad.jp/agreement/
  contact:
    name: Maintainers
    url: https://github.com/sacloud/schema
    email: sacloud.users@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://secure.sakura.ad.jp/cloud/zone/{zone}/api/cloud/1.1
    variables:
      zone:
        default: is1a
        enum:
          - is1a
          - is1b
          - tk1a
          - tk1b
          - tk1v
tags:
  - name: icons
    description: Operations for Icon resource
  - name: regions
    description: Operations for Region resource
  - name: zones
    description: Operations for Zone resource
paths:
  # /icon
  /icon?{params}:
    $ref: './paths/icon/find.yaml'
  /icon:
    $ref: './paths/icon/create.yaml'
  /icon/{iconId}:
    $ref: './paths/icon/actions.yaml'
  # /region
  /region?{params}:
    $ref: './paths/region/find.yaml'
  /region/{regionId}:
    $ref: './paths/region/actions.yaml'
  # /zone
  /zone?{params}:
    $ref: './paths/zone/find.yaml'
  /zone/{zoneId}:
    $ref: './paths/zone/actions.yaml'
security:
  - basicAuth: [ ]
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    $ref: './components/schema/index.yaml'
  responses:
    $ref: './components/responses/index.yaml'
