name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: 'src/v1.1/*.{json,yaml,yml}'
